
title: "Reetika Sarkar"
email: rsarkar@uncg.edu
description: >-
  Personal academic website for Reetika Sarkar, Ph.D. candidate in Statistics.
baseurl: ""
url: "https://reetika-sarkar.github.io"
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
    